name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: exit 0
   lint:
    steps:
      - name: Lint
        run: exit 0
   run:
    steps:
      - name: Test
        run: exit 1

