name: Manual Workflow

on:
  workflow_dispatch:

env:
  TITLE: 'Mr.'
jobs:
  build:
   env:
       FNAME: 'Vinod'
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
    env:
       LNAME: 'Kumar'
        run: echo "$TITLE $FNAME $LNAME"
