name: Manual Workflow

on:
  workflow_dispatch:

env:
  TITLE: 'Mr.'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FNAME: 'Vinod'

    steps:
      - name: Print variables
        env:
          LNAME: 'Kumar'
        run: echo "$TITLE $FNAME $LNAME"
  build2:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: echo "$TITLE $FNAME $LNAME"
