name: Custom Action Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Greeting Action
        uses: ./.github/actions/greet
        with:
          username: Vinod
