name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod

      browser:
        description: "Browser"
        required: true
        default: chromium
        type: choice
        options:
          - chromium
          - firefox
          - webkit

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Environment=${{ inputs.environment }}"
      - run: echo "Browser=${{ inputs.browser }}"
