name: Deploy

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Select deployment environment"
        type: environment
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}

    steps:
      - run: echo "Deploying to ${{ inputs.target }}"
