name: CI Pipeline

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

  unit-test:
    runs-on: ubuntu-latest

  integration-test:
    runs-on: ubuntu-latest

  package:
    needs:
      - lint
      - unit-test
      - integration-test
    runs-on: ubuntu-latest
